name: "github-oidc-demo"
on: 
  workflow_dispatch:
    inputs:
      vault-address:
        required: true
        type: string
        description: Public IP to reach the hashicorp vault
jobs:
    build:
      runs-on: ubuntu-latest
      # This is required for requesting the Github JWT token from the OIDC provide inside this job
      permissions:
        id-token: write 
      # Here we install all the tools needed : Vault CLI and  JFrog CLI
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup JFrog CLI
          uses: jfrog/setup-jfrog-cli@v3
        - name: Run token demo
          run: |
            jf --help