name: "github-oidc-demo"
on: 
  workflow_dispatch:
    inputs:
      vault-endpoint:
        required: true
        type: string
        description: Hashicorp vault endpoint
jobs:
    build:
      runs-on: ubuntu-latest
      # This is required for requesting the Github JWT token from the OIDC provide inside this job
      permissions:
        id-token: write 
      # Here we install all the tools needed : Vault CLI and  JFrog CLI
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup JFrog CLI
          uses: jfrog/setup-jfrog-cli@v3
        - name: Retrieve secret from Vault
          uses: hashicorp/vault-action@v2
            with:
              method: jwt
              url: ${{ github.event.inputs.vault-endpoint }}
              role: gh-vault-jfrog-demo
              secrets: |
                kv-v2/hello foo | DEMO_TOKEN
        - name: Use secret from Vault
          run: |
            echo $DEMO_TOKEN
        - name: Run token demo
          run: |
            jf --help
